### ISSUE TITLE
[M1] Write Proposal - Audience persona section

### ISSUE THREAD

**Issue by qurat-azim** [UBC-MDS/suicide_indicator_r#10]

**Comment by tieandrews** [comment]
First Draft:

**Who are our users?**: Medical professionals such as psychiatrists, nurses, or doctors who want to understand how suicide rates have changed between countries over time.

**What Problem is it Solving for them?**: There is significant data posted like the dataset we are using such as the [Global Mortality database posted by the World Health Organization (WHO)](https://www.who.int/data/data-collection-tools/who-mortality-database) but no easy way to work with it. Our users typically have moderate data/computer literacy so this dashboard allows for them to explore and attempt to answer their own questions easily and efficiently.

**Example Use Cases**:
1. A doctor or nurse working in mental health is considering moving and wants to compare their current countries suicide rate to that of another.
2. A medical professional wants to visualize how suicide rates in their country or surrounding countries have changed  over time.
3. A medical professional wants to dissect the suicide dataset into their population of interest, say by age, date range, region, sex, etc.

**Comment by tieandrews** [comment]
Commpleted on this commit: https://github.com/UBC-MDS/suicide_indicator_r/commit/493aa0681a1c9d3966bc9f956a838256c01dadb9
