### ISSUE TITLE
[Peer Review] User Persona

### ISSUE THREAD

**Issue by ZilongYi** [UBC-MDS/suicide_indicator_r#41]
- Has the dashboard been created with the persona for whom it was designed in mind? Please, read the persona description in the proposal.md before anwsering this question

- Has the dashboard been created with the usage scenario for which it was designed in mind? Please, read the usage scenario description in the proposal.md before anwsering this question

- Suggest at least one more visualization you would include thinking on the persona and usage scenario

**Comment by ZilongYi** [comment]
Repo: https://github.com/UBC-MDS/f1-2021-analysis/tree/v1.0.0
Issue: https://github.ubc.ca/fdandrea/532-peer-review/issues/3

**Comment by qurat-azim** [comment]
completed
