### ISSUE TITLE
[Peer Review] Backend

### ISSUE THREAD

**Issue by ZilongYi** [UBC-MDS/suicide_indicator_r#43]
- Are all the options that you can select in the widgets working correctly? Have you found some options/combinations where you got errors?

- Could be added reactive expressions to avoid code duplication?

- Could be included dynamic UI elements or actions buttons? Or what other element - widget would you include?

**Comment by tieandrews** [comment]
completed, link to comment here: https://github.ubc.ca/fdandrea/532-peer-review/issues/3#issuecomment-23008
