### ISSUE TITLE
[Peer Review] Documentation

### ISSUE THREAD

**Issue by ZilongYi** [UBC-MDS/suicide_indicator_r#44]
- Could you understand from the `README.md `how to use the app? Can the documentation be improved?

- Was the app intuitive to use without reading the documentation? What information could be helpful to include?

- Indicate some change (add or modify a visualization / change the design / include a reactive element) which you would like to include in your own app after reviewing this one

**Comment by ZilongYi** [comment]
Repo: https://github.com/UBC-MDS/f1-2021-analysis/tree/v1.0.0
Issue: https://github.ubc.ca/fdandrea/532-peer-review/issues/3

**Comment by stepanz25** [comment]
completed, link is here: https://github.ubc.ca/fdandrea/532-peer-review/issues/3#issuecomment-23029
