### ISSUE TITLE
Stepan improvement & 1 test

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/suicide_indicator_r#46]

**Comment by stepanz25** [comment]
Improvement: 

- Comment: “The male/female bar chart shows interesting insights. Maybe you can make it possible to select male or female so that if the user wants to know the value for female, they wouldn’t have to subtract the male count from the total.”
    - Added the Radio Button to select by Gender to address following comment:

**Comment by stepanz25** [comment]
Modification: Added the radio button to the side panel to filter by (Female/Male/Both) in the root directory.
Source: Peer Review Milestone 3 ([paste the link to the comment](https://github.ubc.ca/fdandrea/532-peer-review/issues/19#issuecomment-23057))
Team member: Stepan
Commit/s: https://github.com/UBC-MDS/suicide_indicator_r/commit/f13468d917b88788963237c261273812f4d29aa8#diff-a367f167b057eb940cfddb93ab406c9bed6d400bbd71f7650c0f109896b4cfd9 (suicide_indicator_r/app.R file)

**Comment by stepanz25** [comment]
Modification: Added short description to each of the tabs to let the user know what kind of info the user can get from the plots
Source: Peer Review Milestone 3 ([paste the link to the comment](https://github.ubc.ca/fdandrea/532-peer-review/issues/19#issuecomment-23057))
Team member: Stepan
Commit/s: https://github.com/UBC-MDS/suicide_indicator_r/commit/f13468d917b88788963237c261273812f4d29aa8#diff-a367f167b057eb940cfddb93ab406c9bed6d400bbd71f7650c0f109896b4cfd9 (suicide_indicator_r/app.R file)

**Comment by stepanz25** [comment]
Modification: Added short description to each of the tabs to let the user know what kind of info the user can get from the plots
Source: Peer Review Milestone 3 ([paste the link to the comment](https://github.ubc.ca/fdandrea/532-peer-review/issues/19#issuecomment-23057))
Team member: Stepan
Commit/s: https://github.com/UBC-MDS/suicide_indicator_r/commit/f13468d917b88788963237c261273812f4d29aa8#diff-a367f167b057eb940cfddb93ab406c9bed6d400bbd71f7650c0f109896b4cfd9 (suicide_indicator_r/app.R file)

**Comment by stepanz25** [comment]
Modification: Created a test for Country-Wise Comparison Tab
Source: Lectures
Team member: Stepan
Commit/s: https://github.com/UBC-MDS/suicide_indicator_r/commit/7a97655052da2fa0fd3f1bebb07a6b6ae50fd6c9
