### ISSUE TITLE
Update ReadMe with link to app and improved description

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/suicide_indicator_r#51]

**Comment by tieandrews** [comment]
Improve the README.md if you have received feedback about that. Inlcude in yout submission the link to the feedback and the link to the commit/s with the changes.

Please modify your GitHub repo description in the top right corner where it says “About” to include

A short description of your app (might already be there)

The link to your final deployed dashboard (it is often useful to still keep this in the README as well)

A few keywords describing which plots, widgets, and interactions you have used in your dashboards, [like it is done in this demo app](https://github.com/UBC-MDS/dashr-heroku-deployment-demo).

**Comment by stepanz25** [comment]
On my Side:

- Comment: “The male/female bar chart shows interesting insights. Maybe you can make it possible to select male or female so that if the user wants to know the value for female, they wouldn’t have to subtract the male count from the total.”
    - Added the Radio Button to select by Gender to address following comment:

Documentation Improvements and Adjustments (https://github.ubc.ca/fdandrea/532-peer-review/issues/19#issuecomment-23057):


    * Comment: “The dashboard is no longer in planned stage, and it is already been implemented. Perhaps it would be a better idea to remove the dashboard prototype images from the README.md, or move to a separate file/bottom of the file.” 
        * Created an archived folder to place all the documentation/images from the planning stage

    * Comment: ”Perhaps we could consider reordering the headings, starting with the important bit for the user (e.g., "Usage and Deployment Link"), followed by "What can you do with suicide_indicator_r dashboard?", then "Description of the Dashboard" and "Motivation", etc.”
        * Re - organized the structure of the README file from most important to least important for the user
    * Comment: “A short paragraph in each of tab (perhaps in the control panel) describing what the graphs are maybe useful.”
        * Added a short sentences with descriptions into each tab.
